# Generated by Django 2.2.5 on 2020-02-10 04:58

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectmanagent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceFlowModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '接口流程关系',
                'verbose_name_plural': '接口流程关系',
                'db_table': 'interfaceflow_db',
            },
        ),
        migrations.CreateModel(
            name='KeysModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='关键字名')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='关键字值')),
                ('count', models.IntegerField(verbose_name='参数个数')),
                ('params_constraint', jsonfield.fields.JSONField(verbose_name='参数约束[{"paramname":"name"},{"paramname":"height"}\n]')),
                ('keytype', models.IntegerField(choices=[(1, '变量'), (2, '函数'), (3, '运算符')], default=1, verbose_name='关键字类型')),
            ],
            options={
                'verbose_name': '关键字',
                'verbose_name_plural': '关键字',
                'db_table': 'keys_db',
            },
        ),
        migrations.CreateModel(
            name='InterfaceModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='模块名', max_length=20, verbose_name='name')),
                ('top', models.BooleanField(default=False, help_text='置顶', verbose_name='置顶')),
                ('is_delete', models.BooleanField(default=False, help_text='删除', verbose_name='删除')),
                ('project', models.ForeignKey(help_text='项目ID', on_delete=django.db.models.deletion.CASCADE, related_name='inter_module', to='projectmanagent.ProjectManager', verbose_name='项目id')),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块',
                'db_table': 'module_db',
            },
        ),
        migrations.CreateModel(
            name='InterfaceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_type', models.IntegerField(choices=[(1, 'interface'), (2, 'flow')], default=1, help_text='接口类型')),
                ('name', models.CharField(blank=True, help_text='接口名', max_length=20, null=True, verbose_name='name')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('modifier', models.CharField(default='暂定', help_text='修改人', max_length=20, verbose_name='修改人')),
                ('desc', models.TextField(blank=True, help_text='接口描述', max_length=400, null=True, verbose_name='接口描述')),
                ('path_url', models.CharField(blank=True, help_text='接口路径', max_length=200, null=True, verbose_name='接口路径')),
                ('port', models.IntegerField(blank=True, default=8000, help_text='端口', null=True, verbose_name='端口')),
                ('request_protocol', models.IntegerField(blank=True, choices=[(1, 'http'), (2, 'https')], default=1, help_text='请求协议', null=True, verbose_name='请求协议')),
                ('request_way', models.IntegerField(blank=True, choices=[(1, 'get'), (2, 'post'), (3, 'put'), (4, 'delete')], default=1, help_text='请求方式', null=True, verbose_name='请求方式')),
                ('bodyformat', models.IntegerField(blank=True, choices=[(0, 'none'), (1, 'form-data'), (3, 'raw'), (2, 'x-www-form-urlencoded'), (4, 'binary')], help_text='请求体格式', null=True, verbose_name='请求体格式')),
                ('bodymessageformat', models.IntegerField(blank=True, choices=[(1, 'text'), (3, 'javascript'), (2, 'json'), (5, 'html'), (4, 'xml')], help_text='报文格式', null=True, verbose_name='请求报文格式')),
                ('params', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='参数{"key":"value"}')),
                ('headerparams', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='请求头参数')),
                ('bodyparams', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='请求体')),
                ('preprocessing', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='前置处理')),
                ('postprocessing', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='后置处理')),
                ('assertion', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='断言处理')),
                ('intermodule', models.ForeignKey(help_text='模块', on_delete=django.db.models.deletion.CASCADE, related_name='subs_interface', to='interfacemanagement.InterfaceModule', verbose_name='模块')),
                ('process_and_interface', models.ManyToManyField(help_text='关联数据', related_name='flow', through='interfacemanagement.InterfaceFlowModel', to='interfacemanagement.InterfaceModel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_subs_interface', to='projectmanagent.ProjectManager', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '接口',
                'verbose_name_plural': '接口',
                'db_table': 'interface_db',
            },
        ),
        migrations.AddField(
            model_name='interfaceflowmodel',
            name='from_interfacemodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_interface', to='interfacemanagement.InterfaceModel'),
        ),
        migrations.AddField(
            model_name='interfaceflowmodel',
            name='to_interfacemodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_interface', to='interfacemanagement.InterfaceModel'),
        ),
    ]
