# Generated by Django 2.2.5 on 2020-02-11 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfacemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interfaceflowmodel',
            unique_together={('from_interfacemodel', 'to_interfacemodel')},
        ),
    ]
