# Generated by Django 2.2.5 on 2020-02-10 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名称', max_length=20, verbose_name='项目名称')),
                ('start_time', models.CharField(help_text='开始时间', max_length=50, verbose_name='项目开始时间')),
                ('end_time', models.CharField(help_text='结束时间', max_length=50, verbose_name='项目结束时间')),
                ('status', models.BooleanField(default=True, help_text='项目状态 ')),
                ('level', models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高')], default=3, help_text='项目优先级', verbose_name='项目优先级')),
                ('desc', models.TextField(blank=True, help_text='项目描述', max_length=400, null=True, verbose_name='项目描述')),
                ('is_delete', models.BooleanField(default=False, help_text='删除', verbose_name='是否删除')),
                ('person_charge', models.ForeignKey(blank=True, help_text='负责人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='项目负责人')),
            ],
            options={
                'verbose_name': '项目管理',
                'verbose_name_plural': '项目管理',
                'db_table': 'project_manager',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.IntegerField(choices=[(1, '测试环境'), (2, '开发环境'), (3, '预生产环境'), (4, '生产环境')], default=1, help_text='项目环境', verbose_name='环境')),
                ('name', models.CharField(help_text='服务器名', max_length=30, verbose_name='服务器名')),
                ('ip_url', models.CharField(help_text='ip_or_url', max_length=50, verbose_name='ip_or_url')),
                ('desc', models.CharField(help_text='环境描述', max_length=200, verbose_name='环境描述')),
                ('custom_variable', models.CharField(help_text='自定义变量', max_length=30, verbose_name='自定义变量')),
                ('project', models.ForeignKey(help_text='项目Id', on_delete=django.db.models.deletion.CASCADE, related_name='servers_env', to='projectmanagent.ProjectManager', verbose_name='项目')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器',
                'db_table': 'project_server',
                'ordering': ['id'],
                'unique_together': {('project', 'env')},
            },
        ),
        migrations.CreateModel(
            name='ProjectDataServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.IntegerField(choices=[(1, '测试环境'), (2, '开发环境'), (3, '预生产环境'), (4, '生产环境')], default=1, help_text='项目环境', verbose_name='环境')),
                ('name', models.CharField(blank=True, help_text='数据名', max_length=30, verbose_name='数据库名')),
                ('custom_variable', models.CharField(help_text='自定义变量', max_length=30, verbose_name='自定义变量')),
                ('ip', models.GenericIPAddressField(blank=True, help_text='数据库IP', null=True, verbose_name='ip')),
                ('port', models.IntegerField(default=8080, help_text='端口', verbose_name='端口')),
                ('pwd', models.CharField(help_text='密码', max_length=20, verbose_name='密码')),
                ('username', models.CharField(blank=True, help_text='用户名', max_length=30, verbose_name='用户名')),
                ('project', models.ForeignKey(help_text='项目Id', on_delete=django.db.models.deletion.CASCADE, related_name='data_env', to='projectmanagent.ProjectManager', verbose_name='项目')),
            ],
            options={
                'verbose_name': '数据库',
                'verbose_name_plural': '数据库',
                'db_table': 'project_db',
                'ordering': ['id'],
                'unique_together': {('project', 'env')},
            },
        ),
    ]
