# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autotest.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='autotest.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0e\x61utotest.proto\"F\n\x0f\x41utotestRequest\x12\x14\n\x0cinterface_id\x18\x01 \x03(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63\x61se_id\x18\x03 \x03(\x03\"6\n\x10\x41utotestResponse\x12\x14\n\x0cinterface_id\x18\x01 \x03(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t2G\n\x08\x41utoTest\x12;\n\x12\x61utotest_interface\x12\x10.AutotestRequest\x1a\x11.AutotestResponse\"\x00\x62\x06proto3'
)




_AUTOTESTREQUEST = _descriptor.Descriptor(
  name='AutotestRequest',
  full_name='AutotestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interface_id', full_name='AutotestRequest.interface_id', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='AutotestRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='case_id', full_name='AutotestRequest.case_id', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=88,
)


_AUTOTESTRESPONSE = _descriptor.Descriptor(
  name='AutotestResponse',
  full_name='AutotestResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interface_id', full_name='AutotestResponse.interface_id', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='AutotestResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['AutotestRequest'] = _AUTOTESTREQUEST
DESCRIPTOR.message_types_by_name['AutotestResponse'] = _AUTOTESTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AutotestRequest = _reflection.GeneratedProtocolMessageType('AutotestRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUTOTESTREQUEST,
  '__module__' : 'autotest_pb2'
  # @@protoc_insertion_point(class_scope:AutotestRequest)
  })
_sym_db.RegisterMessage(AutotestRequest)

AutotestResponse = _reflection.GeneratedProtocolMessageType('AutotestResponse', (_message.Message,), {
  'DESCRIPTOR' : _AUTOTESTRESPONSE,
  '__module__' : 'autotest_pb2'
  # @@protoc_insertion_point(class_scope:AutotestResponse)
  })
_sym_db.RegisterMessage(AutotestResponse)



_AUTOTEST = _descriptor.ServiceDescriptor(
  name='AutoTest',
  full_name='AutoTest',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=146,
  serialized_end=217,
  methods=[
  _descriptor.MethodDescriptor(
    name='autotest_interface',
    full_name='AutoTest.autotest_interface',
    index=0,
    containing_service=None,
    input_type=_AUTOTESTREQUEST,
    output_type=_AUTOTESTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTOTEST)

DESCRIPTOR.services_by_name['AutoTest'] = _AUTOTEST

# @@protoc_insertion_point(module_scope)
