# Generated by Django 2.2.5 on 2020-02-10 04:58

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interfacemanagement', '0001_initial'),
        ('projectmanagent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(default='文件名', max_length=30, verbose_name='文件名')),
                ('file_name', models.FileField(upload_to='case/', verbose_name='文件路径')),
                ('exclelist', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='数据源列表')),
                ('interface', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='case', to='interfacemanagement.InterfaceModel', verbose_name='接口')),
                ('project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projectmanagent.ProjectManager', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '数据源',
                'verbose_name_plural': '数据源',
                'db_table': 'datasources_db',
                'ordering': ['id'],
            },
        ),
    ]
